version: "3.2"
services:
  web:
    image: antoniohernan/ci
    build:
      cache_from:
        - antoniohernan/ci
      context: .
    depends_on:
      - redis
    ports:
      - 5000:5000
  redis:
    image: redis
